services:
  FYP_ros2:
    image: fyp_ros_image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FYP_ros2_sim
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/Badar_ki_Bhans/ROS_workspaces/FYP_Autonomous_Vehicle/env/AV:/home/user/AV
      # Loading nvim files
      - ~/.config/nvim:/root/.config/nvim
      - /opt/nvim-linux-x86_64:/opt/nvim
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=42
    command: bash
